joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

diff_drive_controller:
  type: diff_drive_controller/DiffDriveController
  left_wheel: ["Revolucionar_2"]
  right_wheel: ["Revolucionar_3"]
  wheel_separation: 0.345   # distância entre suas rodas motorizadas (m)
  wheel_radius:     0.0825  # metade do diâmetro (m)
  cmd_vel_timeout: 0.25
  publish_rate: 50
  enable_odom_tf: true
  base_frame_id: "base_link"
